spring.application.name=gestion-flota
spring.datasource.url=jdbc:postgresql://localhost:5432/db_transcargo
spring.datasource.username=postgres
spring.datasource.password=contrasena
jwt.secret=MiClaveSuperSecretaGestionFlota2026SpringBootJWT

###########
# EMAIL
###########

spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=alexdata89@gmail.com
spring.mail.password=akec gzud jihh raav

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true